### ISSUE TITLE
[Idea / Feature Request] Convert to dds option possible?

### ISSUE THREAD

**Issue by HoJo215** [Backporter/SSE-Fallout-4-Texture-Converter#1]
I was wondering if the "files" used in this tool create the "propriety" swizzle for ps4 dds files?

Tecmo/koei games use type 0x60 - 0x62 dds files on ps4 and wiiu.

gust_tools can extract the GMPK files but shows errors extracting the ps4 G1T file.

So repacking the newly created G1T back into the GMPK will crash the game on ps4 when loading the file.

It was pointed out to me that changing the G1T's header at offset 0x14 to 0B will load the GMPK on the ps4. Confirmed pictured below bikini costume loading kind of on ps4..

Problem is the use of ps4 swizzle not applied puts black blotches on the mod when loaded.

![ff-mod-ps4](https://user-images.githubusercontent.com/61361264/150020084-9696a984-aba1-441a-a256-c9f7c8b7f0b9.jpg)

Could you create an option that converts strictly to dds..
or possibly fill in the blanks to the ps4 swizzle?

This is the last piece of the puzzle to texture modding some tecmo ps4 games.

Here is a ps4 dds and pc dds for comparison.

[files.zip](https://github.com/Backporter/SSE-Fallout-4-Texture-Converter/files/7892430/files.zip)

gust_tools ps4 issues thread.

https://github.com/VitaSmith/gust_tools/issues/54

**Comment by Backporter** [comment]
*(main response)*
This tool is strictly for converting from the most common texture formats(DDS, PNG, TGA, etc) to GNF, going from GNF to DDS would require a totally different tool.

*(notes)*
furthermore a *common* issue that can occur is the game engines don't give a pointer that you are looking at GNF texture data and when you apply a DDS header it will appear to be broken but functional, this is a a issue that needs to be addressed directly in those tools, not this one.

*(secondary response)*
as for images you provided, the PS4 version looks like its been separated. this would explain why the texture data looks different, so are you *sure* the DDS are sizzled in a different way and not just been optimized for the PS4 and the format has changed slightly to account for that?

**Comment by Backporter** [comment]
Its been a month since original post and still no reply, closing the "issue".
